Repository posse-ap/teamdev-2023-posse2-team2D_front, pull requests merged in 2023-05, with the labels that each got.

#32 feat: create toppage
  package-lock.json
  package.json
  src/App.tsx
  src/components/Alertbutton.tsx
  src/components/FullWidthTextField.tsx
  src/components/ImageUpload.tsx
  src/components/SimpleTabs.tsx
  src/components/pages/homePage/HomePage.module.scss
  src/components/pages/homePage/HomePage.tsx
  src/components/pages/sample1Page/Sample1Page.tsx
  src/components/register/RegisterContent.tsx
  src/components/register/RegisterKnowledge.tsx
  src/components/snackbar/AppSnackbar.tsx
  src/components/snackbar/Snackbar.tsx
  src/event_default.jpg
  src/index.tsx
  src/layout/Header.tsx
  src/layout/Layout.tsx
  src/pages/homePage/HomePage.module.scss
  src/pages/homePage/HomePage.tsx
  src/pages/item/Item.module.scss
  src/pages/item/ItemDetail.tsx
  src/pages/item/ItemUpload.tsx
  src/pages/knowledge/KnowledgeDetail.tsx
  src/pages/knowledge/KnowledgeUpload.tsx
  src/pages/sample1Page/Sample1Page.module.scss
  src/pages/sample1Page/Sample1Page.tsx
  src/pages/sample2Page/Sample2Page.module.scss
  src/pages/sample2Page/Sample2Page.tsx
  yarn.lock
Labels: WIP

#39 Feature/8 ブックマーク機能実装
  src/App.tsx
  src/components/register/RegisterContent.tsx
  src/layout/SideMenu.tsx
  src/pages/Bookmark.tsx
Labels: Review Wanted

#40 feat: リクエスト画面作成
  src/App.tsx
  src/pages/homePage/HomePage.module.scss
  src/pages/item/ItemDetail.tsx
  src/pages/request/RequestDetail.tsx
  src/pages/request/RequestList.tsx
Labels: Review Wanted

#41 Feature/15 商品/ナレッジ一覧画面
  src/App.tsx
  src/components/Alertbutton.tsx
  src/components/NotFound.tsx
  src/components/SelectBar.tsx
  src/components/SimpleTabs.tsx
  src/layout/Header.tsx
  src/pages/admin/AllTransactionList.tsx
  src/pages/item/BorrowHistory.tsx
  src/pages/item/Item.module.scss
  src/pages/item/ItemTransactionList.tsx
  src/pages/item/LentHistory.tsx
  src/pages/knowledge/HeldHistory.tsx
  src/pages/knowledge/KnowledgeTransactionList.tsx
  src/pages/knowledge/ParticipationHistory.tsx
Labels: Review Wanted

#42 feat: リクエスト詳細・編集・削除画面
  src/App.tsx
  src/components/Alertbutton.tsx
  src/pages/homePage/HomePage.module.scss
  src/pages/knowledge/HeldHistory.tsx
  src/pages/request/CreateRequest.tsx
  src/pages/request/EditRequest.tsx
  src/pages/request/RequestDetail.tsx
  src/pages/request/RequestList.tsx
Labels: M
